Remove Dockerfile
snakemake/snakefmt pull request #98
Opened 2021-02-14 08:54 UTC by mbhall88

### Removed

- `Dockerfile` has been removed as the [biocontainers](https://hub.docker.com/r/snakemake/snakefmt/tags) images are smaller and some recent changes to the `cryptography` dependency require Rust to be installed (on Alpine) which further bloats our DockerHub image.

2021-02-14 13:10 UTC, bricoletc requested changes
I like this, but think we should still provide an example of how to run the image using docker and singu.

2021-02-14 13:10 UTC, bricoletc commented on README.md
> -docker run -it snakemake/snakefmt snakefmt --help
I like the idea of using bioconda's images- however I believe we should still give an example of how to run it, as here

2021-02-14 13:10 UTC, bricoletc commented on README.md
> -```
Same here, leave in an example of running via singularity

2021-02-14 13:38 UTC, bricoletc commented
Feel free  to merge once the requested changes are in- also, I made a fix to #96 so we could make a new version after I push that in, after this PR is merged

2021-02-15 04:06 UTC, mbhall88 commented
Fair point. I've added an example of using it with both Docker and Singularity.

> I made a fix to #96 in branch fix_96 so we could make a new version after I push that in, after this PR is merged

Perfect. Yep, once you've merged that fix in we can release a new version.

2021-02-15 04:07 UTC, merged